### ISSUE TITLE
Impossible de supprimer des items

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/ListManager_LLA#16]
Quand on choisi de supprimer d'une liste (partagée ou non) j'ai cette erreur:
`Fatal error: Uncaught Error: Call to a member function getSlate() on null in C:\xampp\htdocs\Ubiquity\ListManager\app\controllers\SlateController.php:223 Stack trace: #0 C:\xampp\htdocs\Ubiquity\ListManager\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(150): controllers\SlateController->deleteItem('105', '107') #1 C:\xampp\htdocs\Ubiquity\ListManager\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(111): Ubiquity\controllers\Startup::runAction(Array, true, true) #2 C:\xampp\htdocs\Ubiquity\ListManager\vendor\phpmv\ubiquity\src\Ubiquity\controllers\Startup.php(72): Ubiquity\controllers\Startup::forward('SlateController...') #3 C:\xampp\htdocs\Ubiquity\ListManager\.ubiquity\_index.php(18): Ubiquity\controllers\Startup::run(Array) #4 C:\xampp\htdocs\Ubiquity\ListManager\.ubiquity\.htrouter.php(5): include_once('C:\\xampp\\htdocs...') #5 {main} thrown in C:\xampp\htdocs\Ubiquity\ListManager\app\controllers\SlateController.php on line 223`

Je crois que cela est dû à mon action "deleteItem" qui ne récupère pas l'item car l'id en paramètre est null mais je ne sais pas pourquoi:
https://github.com/dixplo/ListManager_LLA/blob/4c0ef1f11217b566c6b3cb5e532dda527cb4b194/app/controllers/SlateController.php#L220

**Comment by jcheron** [comment]
Vous pouvez me guider un peu pour reproduire votre bug...
Je dois aller à quelle adresse ?
Vous n'avez pas de route pas défaut sur votre projet, on arrive sur la page de base Ubiquity...

**Comment by LeoTexier** [comment]
Il faut choisir une slate avec la route /SlateController et ajouter puis essayer de supprimer un item.

Et pour la route par défaut je sais pas où réglé ce problème.

**Comment by jcheron** [comment]
Dans `app/config/services.php`

**Comment by LeoTexier** [comment]
Problème réglé pour la route par défaut.

**Comment by jcheron** [comment]
voir https://github.com/dixplo/ListManager_LLA/tree/fix-remove-item
Il ne faut pas mettre des `{{script_foot|raw}}` partout...
Ca génère le js, donc c'est une seule fois, et sans ajax, il n'y a pas à le mettre vu qu'il est déjà présent dans le vFooter.html

**Comment by LeoTexier** [comment]
Les Items ne se supprime pas, cependant je crois que j'ai trouvé la source du problème: https://github.com/dixplo/ListManager_LLA/blob/22d95ed1b342e44c7142ffe6418df283a6767195/app/controllers/SlateController.php#L197

Il récupère pas l'id de l'item sélectionné.

**Comment by jcheron** [comment]
Je vous ai mis une version testée qui fonctionne : https://github.com/dixplo/ListManager_LLA/tree/fix-remove-item
Pourquoi vous ne corrigez pas en fonction de ça ?

Cet appel ne retourne rien, ça définit juste la fonction qui va ajouter l'identifiant sur chaque ligne
```php
$dt->setIdentifierFunction('getId'); 
```

**Comment by LeoTexier** [comment]
J'ai pourtant fais un merge pour obtenir les modifications, c'est bizarre.

**Comment by LeoTexier** [comment]
Problème résolu, merci beaucoup !
